### ISSUE TITLE
Functions on WSL?

### ISSUE THREAD

**Issue by lmedini** [powerapi-ng/energy-scripts#3]
Hi, I'm trying to use jouleit on Windows Subsystem for Linux (Windows 10 / WSL2 / Ubuntu 20.04.4 LTS / Intel Core I7), and I get the error:
`find: ‘/sys/devices/virtual/powercap/intel-rapl/intel-rapl:*’: No such file or directory`

I am wondering if your script is supposed to function under WSL, if you are aware of a workaround, if you plan to work on that...

Many thanks in advance!

**Comment by chakib-belgaid** [comment]
hello, unfortunately it doesn't support WSL for the moment
